### ISSUE TITLE
[pro tip] Use setRotation(0,0,0,0) with ComputerCraft to nuke unsuspecting servers!

### ISSUE THREAD

**Issue by FemFruits** [illucc/Kontraption#12]
**BEFORE REPORTING MAKE SURE:**
- [Y] You are on the newest version of Kontraption and Valkyrien Skies.
- [N] You have tested it with only Kontraption, Valkyrien Skies, Mekanism and Kotlin for Forge installed.
- [Y ] The bug hasn't been reported already.

**Describe the bug**
When running "setRotation(0,0,0, 0)" on a computer from CC:Tweaked, it has the unfortunate 100% guarantee of ruining the life of whoever runs that server by destroying server TPS and resulting in a VS physics thread crash.

**To Reproduce**
1. Launch Minecraft
2. Join an unsuspecting multiplayer server or create a single player world
3. Create a VS ship with an advanced computer, gyro, energy cube and ship control interface
4. Open up the computer, get the control interface to a variable so you can control it
5. Enjoy the VS physics thread crashing as well as a lot of TPS lag
6. Profit?

**Expected behavior**
I expected the ship to rotate so it stays upright (although this might also not be correct as I don't still fully understand CC for this)

**Screenshots/videos**
The ship I made
![image](https://github.com/illucc/Kontraption/assets/132680900/c1da888e-b9b0-4fd9-ad4f-a9a3a682da20)

**Logs**
[latest.log](https://github.com/illucc/Kontraption/files/13654064/latest.log)
[debug.log](https://github.com/illucc/Kontraption/files/13654066/debug.log)

**Versions**
 - VS2 version: 2.1.1-beta.2
 - Mekanism version: 10.2.5

**Additional context**
Since this is a problem with CC:Tweaked support, I have added CC:Tweaked to the pack I was testing with.

**Comment by illucc** [comment]
Quaternion with a value of 0 0 0 0 is not a valid quaternion and that might be crashing the phys thread. I will implement a thing to prevent that from happening 👍.
For now use 0 0 0 1 to set the ship rotation to 0

**Comment by illucc** [comment]
Fixed in https://github.com/illucc/Kontraption/commit/44e5cd0f5fb14c515702c5ab2d7ff29b26e62d07
