### ISSUE TITLE
Rubidium and Oculus break

### ISSUE THREAD

**Issue by Parronna** [illucc/Kontraption#19]
**BEFORE REPORTING MAKE SURE:**
- [Y] You are on the newest version of Kontraption and Valkyrien Skies.
- [Y and N] You have tested it with only Kontraption, Valkyrien Skies, Mekanism and Kotlin for Forge installed.
- [Y] The bug hasn't been reported already.

**Describe the bug**
With Rubidium and Oculus, the connected textures are broken.

**To Reproduce**
Just place thrusters and vomit

**Expected behavior**
I expected to have connected textures

**Screenshots/videos**
![image](https://github.com/illucc/Kontraption/assets/151066461/1583f8b6-2f1a-4518-847f-245a90c007be)

**Logs**
not a crash

**Versions**
 - VS2 version: beta.6 (built from github)
 - Mekanism version: 10.2.5

**Comment by illucc** [comment]
do you have the https://www.curseforge.com/minecraft/mc-mods/ctm mod?

**Comment by illucc** [comment]
not a kontraption bug, press f3+a to fix the connected textures being wacky
