### ISSUE TITLE
ion engines use (noble) gases as fuel

### ISSUE THREAD

**Issue by A765-ALEX** [illucc/Kontraption#25]
**Is your feature request related to a problem? Please describe.**
so that they aren't too overpowered

**Describe the solution you'd like**
ion engines use a miniscule amount of fuel e.g. helium, neon, argon, xenon etc.

**Describe alternatives you've considered**
alternatively keep them the way they are

**Additional context**
irl ion thrusters use real noble gases as fuel so bonus points for realism :+1:

**Comment by PriestOfFern** [comment]
Mekanism doesn’t have any of those gases, so it’ll require figuring out how to make them craftable

Also ion thrusters are already annoying to connect power to, so I can’t imagine having to connect gas pipes on top of that

And that’s ignoring the fact that ion thrusters aren’t actually overpowered at all? They’re expensive and produce tiny amounts of thrust, so shoving a gas cost on top makes them pretty much useless compared to liquid fuel thrusters

**Comment by A765-ALEX** [comment]
alr, guess that's true
well, then I can close this

čet, 21. mar 2024. 17:44 PriestOfFerns ***@***.***> je
napisao/la:

**Comment by A765-ALEX** [comment]
alr, guess that's true
well I'ma just close this then
