### ISSUE TITLE
Not server ready - tries to load level rendered in dedicated servers? 

### ISSUE THREAD

**Issue by AlexBeez** [illucc/Kontraption#27]
**BEFORE REPORTING MAKE SURE:**
- [ Y ] You are on the newest version of Kontraption and Valkyrien Skies.
- [ N - not sure if relevant? ] You have tested it with only Kontraption, Valkyrien Skies, Mekanism and Kotlin for Forge installed.
- [ Y ] The bug hasn't been reported already.

**Describe the bug**
When loading the mod in a dedicated server, it attempts loading class LevelRenderer, which is not valid. 

**To Reproduce**
1. Install Kontraption and all prerequisites on a dedicated server
2. Attempt running dedicated server
3. Observe server logs as it fails to launch

**Expected behavior**
The mod detects it is running in a DEDICATED_SERVER environment and does not attempt to load rendering classes

**Screenshots/videos**
![image](https://github.com/mrsterner/Kontraption/assets/44407345/8dfe7500-b938-47ff-b106-d6c7548c8ec3)

**Logs**
https://mclo.gs/d9ohONr

**Versions**
 - VS2 version: 2.3.0_beta5 (latest as of right now
 - Mekanism version: 10.4.6

**Additional context**
N/A

**Comment by illucc** [comment]
im not working on kontraption anymore, it will be months if not years until i get back to it if i even get back to it at all, im sorry

**Comment by AlexBeez** [comment]
> im not working on kontraption anymore, it will be months if not years until i get back to it if i even get back to it at all, im sorry

no problem fam! if anything thanks for taking the time to confirm that.

You go and take care, may life be kind to you!

**Comment by illucc** [comment]
fixed in https://github.com/mrsterner/Kontraption/commit/15bafd80690c5eb49bf7ca685424b939b92a96ac
