### ISSUE TITLE
Valkyrien Computers Crash

### ISSUE THREAD

**Issue by Rulft44** [illucc/Kontraption#3]
[crash-2023-11-18_19.18.10-fml.txt](https://github.com/illucc/Kontraption/files/13401354/crash-2023-11-18_19.18.10-fml.txt)
Minecraft crashed with Valkyrien Computers, crash report above ^

**Comment by illucc** [comment]
VS computers doesn't support the newest version of VS2 as far as I know.
Also please use the bug report template next time.
