### ISSUE TITLE
When thrusters activate after rejoining a world, the ship teleports to bedrock

### ISSUE THREAD

**Issue by gamegude** [illucc/Kontraption#55]
**Describe the bug**
When activating thrusters it teleports to bedrock level

**To Reproduce**
1. make a superflat world (default preset)
2. make a thruster and and assemble it
3. rejoin the world
4. when the thrusters activated the ship teleports to bedrock level

**Expected behavior**
Ship Teleports to bedrock level

**Screenshots/videos**
-

**Logs**
The game logs (latest.log, debug.log).

**Versions**
 - VS2 version: 2.3.0-beta.5
 - Mekanism version: 10.4.11.67

**Additional context**
-

**Comment by WaterOtter86** [comment]
Ok dats bad BC it may be vs bug

**Comment by illucc** [comment]
its maybe the ships being loaded before the world and its collisions get loaded thing

**Comment by gamegude** [comment]
So how do i fix it?

**Comment by illucc** [comment]
idk :(
prob needs a fix on the vs side, but on normal worlds it shouldnt affect it that much hopefully, unless the ship is on a 1 block thick platform

**Comment by gamegude** [comment]
alr ill close this p

**Comment by gamegude** [comment]
ima close this now thanks
