### ISSUE TITLE
Lame bug report 3: dj edition (BIG THRUSTER FORGOR)

### ISSUE THREAD

**Issue by awesomebossdj7** [illucc/Kontraption#8]
**BEFORE REPORTING MAKE SURE:**
- [x] You are on the newest version of Kontraption and Valkyrien Skies.
- [x] You have tested it with only Kontraption, Valkyrien Skies, Mekanism and Kotlin for Forge installed.
- [x] The bug hasn't been reported already.

**Describe the bug**
world corruption when building a liquid fuel thruster

**To Reproduce**
NOT ON SHIP, build a liquid fuel thruster

**Expected behavior**
world not corrupt and game not crash

**Comment by illucc** [comment]
fixed in https://github.com/illucc/Kontraption/commit/1721079c873b337460747591559da6408f959c26
