### ISSUE TITLE
Rotating Ion Thrusters with Debug Stick

### ISSUE THREAD

**Issue by Rulft44** [illucc/Kontraption#9]
**Describe the bug**
Basically, when using the Debug Stick on an Ion Thruster to rotate it, the thruster stops working.

**To Reproduce**
1. Give yourself a debug stick (`/give @s minecraft:debug_stick 1`)
2. Place an Ion Thruster
3. R-click the thruster with the stick to rotate it
4. Give it power
5. (Ps: on a ship ofc)

**Expected behavior**
Rotate the thruster without it stoping to work

**Screenshots/videos**
...

**Logs**
The game logs (latest.log, debug.log).

**Versions**
 - VS2 version: latest on vs discord (valkyrienskies-118-forge-2.1.1-beta.3e00ea733a3)
 - Mekanism version: Mekanism-1.18.2-10.2.5.465

**Additional context**
...

**Comment by illucc** [comment]
Probably wont fix since the debug stick is a creative item and when you're in creative you can simply break and replace the block
